// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_voila_faceVoila_Fa000_Ctr000 = polygon({ points: [ [ -10.0000, -25.0000 ],
	[ 20.0000, -25.0000 ],
	[ 20.0000, 15.0000 ],
	[ 19.8481, 16.7365 ],
	[ 19.3969, 18.4202 ],
	[ 18.6603, 20.0000 ],
	[ 17.6604, 21.4279 ],
	[ 16.4279, 22.6604 ],
	[ 15.0000, 23.6603 ],
	[ 13.4202, 24.3969 ],
	[ 11.7365, 24.8481 ],
	[ 10.0000, 25.0000 ],
	[ -20.0000, 25.0000 ],
	[ -20.0000, -15.0000 ],
	[ -19.8079, -16.9509 ],
	[ -19.2388, -18.8268 ],
	[ -18.3147, -20.5557 ],
	[ -17.0711, -22.0711 ],
	[ -15.5557, -23.3147 ],
	[ -13.8268, -24.2388 ],
	[ -11.9509, -24.8079 ],
	[ -10.0000, -25.0000 ] ] });

const ctr_face_fig_voila_faceVoila_Fa000_Ctr001 = polygon({ points: [ [ 10.0000, 0.0000 ],
	[ 9.8079, 1.9509 ],
	[ 9.2388, 3.8268 ],
	[ 8.3147, 5.5557 ],
	[ 7.0711, 7.0711 ],
	[ 5.5557, 8.3147 ],
	[ 3.8268, 9.2388 ],
	[ 1.9509, 9.8079 ],
	[ 0.0000, 10.0000 ],
	[ -1.9509, 9.8079 ],
	[ -3.8268, 9.2388 ],
	[ -5.5557, 8.3147 ],
	[ -7.0711, 7.0711 ],
	[ -8.3147, 5.5557 ],
	[ -9.2388, 3.8268 ],
	[ -9.8079, 1.9509 ],
	[ -10.0000, 0.0000 ],
	[ -9.8079, -1.9509 ],
	[ -9.2388, -3.8268 ],
	[ -8.3147, -5.5557 ],
	[ -7.0711, -7.0711 ],
	[ -5.5557, -8.3147 ],
	[ -3.8268, -9.2388 ],
	[ -1.9509, -9.8079 ],
	[ -0.0000, -10.0000 ],
	[ 1.9509, -9.8079 ],
	[ 3.8268, -9.2388 ],
	[ 5.5557, -8.3147 ],
	[ 7.0711, -7.0711 ],
	[ 8.3147, -5.5557 ],
	[ 9.2388, -3.8268 ],
	[ 9.8079, -1.9509 ],
	[ 10.0000, 0.0000 ] ] });

face_fig_voila_faceVoila_Fa000 = subtract( ctr_face_fig_voila_faceVoila_Fa000_Ctr000, ctr_face_fig_voila_faceVoila_Fa000_Ctr001 );
fig_voila_faceVoila = face_fig_voila_faceVoila_Fa000;

const subpax_voila_top =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 10}, fig_voila_faceVoila )
		)
	);

const pax_voila = subpax_voila_top;

return pax_voila;
}
module.exports = { main };
