// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_surface_faceSurface_Fa000_Ctr000 = polygon({ points: [ [ -4353.3333, -500.0000 ],
	[ -2753.3333, -500.0000 ],
	[ -2753.3333, 500.0000 ],
	[ -4353.3333, 500.0000 ],
	[ -4353.3333, -500.0000 ] ] });

face_fig_surface_faceSurface_Fa000 = ctr_face_fig_surface_faceSurface_Fa000_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa001_Ctr000 = polygon({ points: [ [ -2743.3333, -1510.0000 ],
	[ -1143.3333, -1510.0000 ],
	[ -1143.3333, -510.0000 ],
	[ -2743.3333, -510.0000 ],
	[ -2743.3333, -1510.0000 ] ] });

face_fig_surface_faceSurface_Fa001 = ctr_face_fig_surface_faceSurface_Fa001_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa002_Ctr000 = polygon({ points: [ [ -2743.3333, -500.0000 ],
	[ -1143.3333, -500.0000 ],
	[ -1143.3333, 500.0000 ],
	[ -2743.3333, 500.0000 ],
	[ -2743.3333, -500.0000 ] ] });

face_fig_surface_faceSurface_Fa002 = ctr_face_fig_surface_faceSurface_Fa002_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa003_Ctr000 = polygon({ points: [ [ -2743.3333, 510.0000 ],
	[ -1143.3333, 510.0000 ],
	[ -1143.3333, 1510.0000 ],
	[ -2743.3333, 1510.0000 ],
	[ -2743.3333, 510.0000 ] ] });

face_fig_surface_faceSurface_Fa003 = ctr_face_fig_surface_faceSurface_Fa003_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa004_Ctr000 = polygon({ points: [ [ -800.0000, -2520.0000 ],
	[ 800.0000, -2520.0000 ],
	[ 800.0000, -1520.0000 ],
	[ -800.0000, -1520.0000 ],
	[ -800.0000, -2520.0000 ] ] });

face_fig_surface_faceSurface_Fa004 = ctr_face_fig_surface_faceSurface_Fa004_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa005_Ctr000 = polygon({ points: [ [ -800.0000, -1510.0000 ],
	[ 800.0000, -1510.0000 ],
	[ 800.0000, -510.0000 ],
	[ -800.0000, -510.0000 ],
	[ -800.0000, -1510.0000 ] ] });

face_fig_surface_faceSurface_Fa005 = ctr_face_fig_surface_faceSurface_Fa005_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa006_Ctr000 = polygon({ points: [ [ -800.0000, -500.0000 ],
	[ 800.0000, -500.0000 ],
	[ 800.0000, 500.0000 ],
	[ -800.0000, 500.0000 ],
	[ -800.0000, -500.0000 ] ] });

face_fig_surface_faceSurface_Fa006 = ctr_face_fig_surface_faceSurface_Fa006_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa007_Ctr000 = polygon({ points: [ [ -800.0000, 510.0000 ],
	[ 800.0000, 510.0000 ],
	[ 800.0000, 1510.0000 ],
	[ -800.0000, 1510.0000 ],
	[ -800.0000, 510.0000 ] ] });

face_fig_surface_faceSurface_Fa007 = ctr_face_fig_surface_faceSurface_Fa007_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa008_Ctr000 = polygon({ points: [ [ -800.0000, 1520.0000 ],
	[ 800.0000, 1520.0000 ],
	[ 800.0000, 2520.0000 ],
	[ -800.0000, 2520.0000 ],
	[ -800.0000, 1520.0000 ] ] });

face_fig_surface_faceSurface_Fa008 = ctr_face_fig_surface_faceSurface_Fa008_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa009_Ctr000 = polygon({ points: [ [ 1143.3333, -1510.0000 ],
	[ 2743.3333, -1510.0000 ],
	[ 2743.3333, -510.0000 ],
	[ 1143.3333, -510.0000 ],
	[ 1143.3333, -1510.0000 ] ] });

face_fig_surface_faceSurface_Fa009 = ctr_face_fig_surface_faceSurface_Fa009_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa010_Ctr000 = polygon({ points: [ [ 1143.3333, -500.0000 ],
	[ 2743.3333, -500.0000 ],
	[ 2743.3333, 500.0000 ],
	[ 1143.3333, 500.0000 ],
	[ 1143.3333, -500.0000 ] ] });

face_fig_surface_faceSurface_Fa010 = ctr_face_fig_surface_faceSurface_Fa010_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa011_Ctr000 = polygon({ points: [ [ 1143.3333, 510.0000 ],
	[ 2743.3333, 510.0000 ],
	[ 2743.3333, 1510.0000 ],
	[ 1143.3333, 1510.0000 ],
	[ 1143.3333, 510.0000 ] ] });

face_fig_surface_faceSurface_Fa011 = ctr_face_fig_surface_faceSurface_Fa011_Ctr000;
const ctr_face_fig_surface_faceSurface_Fa012_Ctr000 = polygon({ points: [ [ 2753.3333, -500.0000 ],
	[ 4353.3333, -500.0000 ],
	[ 4353.3333, 500.0000 ],
	[ 2753.3333, 500.0000 ],
	[ 2753.3333, -500.0000 ] ] });

face_fig_surface_faceSurface_Fa012 = ctr_face_fig_surface_faceSurface_Fa012_Ctr000;
fig_surface_faceSurface = union( face_fig_surface_faceSurface_Fa000, face_fig_surface_faceSurface_Fa001, face_fig_surface_faceSurface_Fa002, face_fig_surface_faceSurface_Fa003, face_fig_surface_faceSurface_Fa004, face_fig_surface_faceSurface_Fa005, face_fig_surface_faceSurface_Fa006, face_fig_surface_faceSurface_Fa007, face_fig_surface_faceSurface_Fa008, face_fig_surface_faceSurface_Fa009, face_fig_surface_faceSurface_Fa010, face_fig_surface_faceSurface_Fa011, face_fig_surface_faceSurface_Fa012 );
const ctr_face_fig_surface_faceOnePanel_Fa000_Ctr000 = polygon({ points: [ [ 0.0000, 0.0000 ],
	[ 1600.0000, 0.0000 ],
	[ 1600.0000, 1000.0000 ],
	[ 0.0000, 1000.0000 ],
	[ 0.0000, 0.0000 ] ] });

face_fig_surface_faceOnePanel_Fa000 = ctr_face_fig_surface_faceOnePanel_Fa000_Ctr000;
fig_surface_faceOnePanel = face_fig_surface_faceOnePanel_Fa000;

const subpax_surface_panel_0 =
	translate( [ -4353.333333333333, -500, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_1 =
	translate( [ -2743.333333333333, -1510, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_2 =
	translate( [ -2743.333333333333, -500, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_3 =
	translate( [ -2743.333333333333, 510, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_4 =
	translate( [ -799.9999999999998, -2520, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_5 =
	translate( [ -799.9999999999998, -1510, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_6 =
	translate( [ -799.9999999999998, -500, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_7 =
	translate( [ -799.9999999999998, 510, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_8 =
	translate( [ -799.9999999999998, 1520, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_9 =
	translate( [ 1143.3333333333337, -1510, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_10 =
	translate( [ 1143.3333333333337, -500, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_11 =
	translate( [ 1143.3333333333337, 510, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);


const subpax_surface_panel_12 =
	translate( [ 2753.333333333334, -500, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 40}, fig_surface_faceOnePanel )
		)
	);

const pax_surface = union( subpax_surface_panel_0, subpax_surface_panel_1, subpax_surface_panel_2, subpax_surface_panel_3, subpax_surface_panel_4, subpax_surface_panel_5, subpax_surface_panel_6, subpax_surface_panel_7, subpax_surface_panel_8, subpax_surface_panel_9, subpax_surface_panel_10, subpax_surface_panel_11, subpax_surface_panel_12 );

return pax_surface;
}
module.exports = { main };
